### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by gerkensm** [lqs469/slate-table#1]
I like this plugin - it would be perfect for a project I'm working on! However, I cannot seem to find the license under which it is distributed. Could you add that to the repository or let me know? Thanks in advance

**Comment by lqs469** [comment]
> I like this plugin - it would be perfect for a project I'm working on! However, I cannot seem to find the license under which it is distributed. Could you add that to the repository or let me know? Thanks in advance

Thanks for the comment, I will do it.

**Comment by lqs469** [comment]
Add the MIT license and close the issue.
